// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bid.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// TODO: deprecated.
type OrderType int32

const (
	OrderType_ANY OrderType = 0
	OrderType_BID OrderType = 1
	OrderType_ASK OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ANY",
	1: "BID",
	2: "ASK",
}
var OrderType_value = map[string]int32{
	"ANY": 0,
	"BID": 1,
	"ASK": 2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Geo represent GeoIP results for node
type Geo struct {
	Country string  `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	City    string  `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	Lat     float32 `protobuf:"fixed32,3,opt,name=lat" json:"lat,omitempty"`
	Lon     float32 `protobuf:"fixed32,4,opt,name=lon" json:"lon,omitempty"`
}

func (m *Geo) Reset()                    { *m = Geo{} }
func (m *Geo) String() string            { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()               {}
func (*Geo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Geo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Geo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Geo) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Geo) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

// TODO: deprecated.
type Resources struct {
	// CPU core count
	CpuCores uint64 `protobuf:"varint,1,opt,name=cpuCores" json:"cpuCores,omitempty"`
	// RAM, in bytes
	RamBytes uint64 `protobuf:"varint,2,opt,name=ramBytes" json:"ramBytes,omitempty"`
	// GPU devices count
	GpuCount GPUCount `protobuf:"varint,3,opt,name=gpuCount,enum=sonm.GPUCount" json:"gpuCount,omitempty"`
	// todo: discuss
	// storage volume, in Megabytes
	Storage uint64 `protobuf:"varint,4,opt,name=storage" json:"storage,omitempty"`
	// Inbound network traffic (the higher value), in bytes
	NetTrafficIn uint64 `protobuf:"varint,5,opt,name=netTrafficIn" json:"netTrafficIn,omitempty"`
	// Outbound network traffic (the higher value), in bytes
	NetTrafficOut uint64 `protobuf:"varint,6,opt,name=netTrafficOut" json:"netTrafficOut,omitempty"`
	// Allowed network connections
	NetworkType NetworkType `protobuf:"varint,7,opt,name=networkType,enum=sonm.NetworkType" json:"networkType,omitempty"`
	// Other properties/benchmarks. The higher means better.
	Properties map[string]float64 `protobuf:"bytes,8,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *Resources) Reset()                    { *m = Resources{} }
func (m *Resources) String() string            { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()               {}
func (*Resources) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Resources) GetCpuCores() uint64 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *Resources) GetRamBytes() uint64 {
	if m != nil {
		return m.RamBytes
	}
	return 0
}

func (m *Resources) GetGpuCount() GPUCount {
	if m != nil {
		return m.GpuCount
	}
	return GPUCount_NO_GPU
}

func (m *Resources) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *Resources) GetNetTrafficIn() uint64 {
	if m != nil {
		return m.NetTrafficIn
	}
	return 0
}

func (m *Resources) GetNetTrafficOut() uint64 {
	if m != nil {
		return m.NetTrafficOut
	}
	return 0
}

func (m *Resources) GetNetworkType() NetworkType {
	if m != nil {
		return m.NetworkType
	}
	return NetworkType_NO_NETWORK
}

func (m *Resources) GetProperties() map[string]float64 {
	if m != nil {
		return m.Properties
	}
	return nil
}

// TODO: deprecated.
type Slot struct {
	// Buyer’s rating. Got from Buyer’s profile for BID orders rating_supplier.
	BuyerRating int64 `protobuf:"varint,1,opt,name=buyerRating" json:"buyerRating,omitempty"`
	// Supplier’s rating. Got from Supplier’s profile for ASK orders.
	SupplierRating int64 `protobuf:"varint,2,opt,name=supplierRating" json:"supplierRating,omitempty"`
	// Geo represent Worker's position
	Geo *Geo `protobuf:"bytes,3,opt,name=geo" json:"geo,omitempty"`
	// Hardware resources requirements
	Resources *Resources `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
	// Duration is resource rent duration in seconds
	Duration uint64 `protobuf:"varint,5,opt,name=duration" json:"duration,omitempty"`
}

func (m *Slot) Reset()                    { *m = Slot{} }
func (m *Slot) String() string            { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()               {}
func (*Slot) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Slot) GetBuyerRating() int64 {
	if m != nil {
		return m.BuyerRating
	}
	return 0
}

func (m *Slot) GetSupplierRating() int64 {
	if m != nil {
		return m.SupplierRating
	}
	return 0
}

func (m *Slot) GetGeo() *Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Slot) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Slot) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// TODO: deprecated.
type Order struct {
	// Order ID, UUIDv4
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Buyer's EtherumID
	BuyerID string `protobuf:"bytes,2,opt,name=buyerID" json:"buyerID,omitempty"`
	// Supplier's is EtherumID
	SupplierID string `protobuf:"bytes,3,opt,name=supplierID" json:"supplierID,omitempty"`
	// Order type (Bid or Ask)
	OrderType OrderType `protobuf:"varint,5,opt,name=orderType,enum=sonm.OrderType" json:"orderType,omitempty"`
	// Slot describe resource requiements
	Slot *Slot `protobuf:"bytes,6,opt,name=slot" json:"slot,omitempty"`
	// PricePerSecond specifies order price for ordered resources per second.
	PricePerSecond *BigInt `protobuf:"bytes,7,opt,name=pricePerSecond" json:"pricePerSecond,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetBuyerID() string {
	if m != nil {
		return m.BuyerID
	}
	return ""
}

func (m *Order) GetSupplierID() string {
	if m != nil {
		return m.SupplierID
	}
	return ""
}

func (m *Order) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ANY
}

func (m *Order) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (m *Order) GetPricePerSecond() *BigInt {
	if m != nil {
		return m.PricePerSecond
	}
	return nil
}

func init() {
	proto.RegisterType((*Geo)(nil), "sonm.Geo")
	proto.RegisterType((*Resources)(nil), "sonm.Resources")
	proto.RegisterType((*Slot)(nil), "sonm.Slot")
	proto.RegisterType((*Order)(nil), "sonm.Order")
	proto.RegisterEnum("sonm.OrderType", OrderType_name, OrderType_value)
}

func init() { proto.RegisterFile("bid.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0xcd, 0x47, 0x77, 0x37, 0x27, 0x6b, 0x5b, 0x0f, 0x5e, 0x84, 0x0a, 0x6b, 0x29, 0xb2,
	0x94, 0x05, 0x7b, 0x91, 0xf5, 0x42, 0x04, 0x11, 0x6b, 0x65, 0x29, 0xc2, 0xb6, 0x4c, 0x57, 0xc4,
	0xcb, 0x34, 0x99, 0x0d, 0xc3, 0x76, 0x67, 0xc2, 0x64, 0xa2, 0xf4, 0x0d, 0x7c, 0x24, 0x9f, 0xc4,
	0xe7, 0x91, 0x39, 0x69, 0xd2, 0x6e, 0xef, 0xe6, 0xfc, 0xce, 0x7f, 0x72, 0x3e, 0xfe, 0x13, 0x08,
	0xd6, 0x22, 0x9b, 0x14, 0x5a, 0x19, 0x85, 0x7e, 0xa9, 0xe4, 0xe3, 0xe0, 0x7c, 0x2d, 0x72, 0x21,
	0x4d, 0xcd, 0x06, 0x3d, 0x21, 0x2d, 0x95, 0x22, 0xa9, 0xc1, 0xe8, 0x07, 0x78, 0x37, 0x5c, 0x61,
	0x04, 0xa7, 0xa9, 0xaa, 0xa4, 0xd1, 0xdb, 0xc8, 0x19, 0x3a, 0xe3, 0x80, 0x35, 0x21, 0x22, 0xf8,
	0xa9, 0x30, 0xdb, 0xc8, 0x25, 0x4c, 0x67, 0xec, 0x83, 0xb7, 0x49, 0x4c, 0xe4, 0x0d, 0x9d, 0xb1,
	0xcb, 0xec, 0x91, 0x88, 0x92, 0x91, 0xbf, 0x23, 0x4a, 0x8e, 0xfe, 0x78, 0x10, 0x30, 0x5e, 0xaa,
	0x4a, 0xa7, 0xbc, 0xc4, 0x01, 0x9c, 0xa5, 0x45, 0xf5, 0x45, 0x69, 0x5e, 0x52, 0x01, 0x9f, 0xb5,
	0xb1, 0xcd, 0xe9, 0xe4, 0x71, 0xba, 0x35, 0xbc, 0xa4, 0x2a, 0x3e, 0x6b, 0x63, 0xbc, 0x82, 0xb3,
	0xdc, 0xea, 0x2a, 0x59, 0x97, 0xeb, 0xc6, 0xdd, 0x89, 0x1d, 0x60, 0x72, 0xb3, 0xfc, 0x4e, 0x94,
	0xb5, 0x79, 0x3b, 0x43, 0x69, 0x94, 0x4e, 0x72, 0x4e, 0x7d, 0xf8, 0xac, 0x09, 0x71, 0x04, 0xe7,
	0x92, 0x9b, 0x3b, 0x9d, 0xdc, 0xdf, 0x8b, 0x74, 0x2e, 0xa3, 0x0e, 0xa5, 0x9f, 0x30, 0x7c, 0x03,
	0xcf, 0xf7, 0xf1, 0xa2, 0x32, 0xd1, 0x09, 0x89, 0x9e, 0x42, 0xbc, 0x86, 0x50, 0x72, 0xf3, 0x5b,
	0xe9, 0x87, 0xbb, 0x6d, 0xc1, 0xa3, 0x53, 0x6a, 0xe9, 0x45, 0xdd, 0xd2, 0xed, 0x3e, 0xc1, 0x0e,
	0x55, 0xf8, 0x09, 0xa0, 0xd0, 0xaa, 0xe0, 0xda, 0x08, 0x5e, 0x46, 0x67, 0x43, 0x6f, 0x1c, 0xc6,
	0xaf, 0xeb, 0x3b, 0xed, 0x86, 0x26, 0xcb, 0x56, 0xf1, 0xd5, 0xee, 0x9d, 0x1d, 0x5c, 0x19, 0x7c,
	0x84, 0xde, 0x51, 0xda, 0x2e, 0xfc, 0x81, 0x37, 0x66, 0xd9, 0x23, 0xbe, 0x84, 0xce, 0xaf, 0x64,
	0x53, 0x71, 0xda, 0xa1, 0xc3, 0xea, 0xe0, 0x83, 0xfb, 0xde, 0x19, 0xfd, 0x75, 0xc0, 0x5f, 0x6d,
	0x94, 0xc1, 0x21, 0x84, 0xeb, 0x6a, 0xcb, 0x35, 0x4b, 0x8c, 0x90, 0x39, 0x5d, 0xf6, 0xd8, 0x21,
	0xc2, 0x4b, 0xe8, 0x96, 0x55, 0x51, 0x6c, 0x44, 0x2b, 0x72, 0x49, 0x74, 0x44, 0xf1, 0x15, 0x78,
	0x39, 0x57, 0x64, 0x49, 0x18, 0x07, 0x3b, 0x4b, 0xb8, 0x62, 0x96, 0xe2, 0x5b, 0x08, 0x74, 0x33,
	0x17, 0x59, 0x11, 0xc6, 0xbd, 0xa3, 0x71, 0xd9, 0x5e, 0x61, 0xfd, 0xcf, 0x2a, 0x9d, 0x18, 0xa1,
	0x1a, 0x67, 0xda, 0x78, 0xf4, 0xcf, 0x81, 0xce, 0x42, 0x67, 0x5c, 0x63, 0x17, 0x5c, 0x91, 0xed,
	0xe6, 0x75, 0x45, 0x66, 0xdd, 0xa6, 0xc6, 0xe7, 0xb3, 0xdd, 0xd3, 0x6c, 0x42, 0xbc, 0x00, 0x68,
	0xba, 0x9d, 0xcf, 0xa8, 0xc5, 0x80, 0x1d, 0x10, 0xdb, 0x9e, 0xb2, 0x9f, 0x24, 0x07, 0x3b, 0xe4,
	0xe0, 0xae, 0xbd, 0x45, 0x83, 0xd9, 0x5e, 0x81, 0x17, 0xe0, 0x97, 0x1b, 0x55, 0xbf, 0x87, 0x30,
	0x86, 0x5a, 0x69, 0xd7, 0xc9, 0x88, 0xe3, 0x3b, 0xe8, 0x16, 0x5a, 0xa4, 0x7c, 0xc9, 0xf5, 0x8a,
	0xa7, 0x4a, 0x66, 0xf4, 0x2a, 0xc2, 0xf8, 0xbc, 0x56, 0x4e, 0x45, 0x3e, 0x97, 0x86, 0x1d, 0x69,
	0xae, 0x2e, 0x21, 0x68, 0xab, 0xe1, 0x29, 0x78, 0x9f, 0x6f, 0x7f, 0xf6, 0x9f, 0xd9, 0xc3, 0x74,
	0x3e, 0xeb, 0x3b, 0x44, 0x56, 0xdf, 0xfa, 0xee, 0xfa, 0x84, 0x7e, 0xd3, 0xeb, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0x7f, 0x1a, 0x6c, 0xd8, 0x03, 0x00, 0x00,
}
