// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dwh.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// grpccmd imports
import (
	"io"

	"github.com/spf13/cobra"
	"github.com/sshaman1101/grpccmd"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ComparisonOperator int32

const (
	ComparisonOperator_EQ  ComparisonOperator = 0
	ComparisonOperator_GTE ComparisonOperator = 1
	ComparisonOperator_LTE ComparisonOperator = 2
)

var ComparisonOperator_name = map[int32]string{
	0: "EQ",
	1: "GTE",
	2: "LTE",
}
var ComparisonOperator_value = map[string]int32{
	"EQ":  0,
	"GTE": 1,
	"LTE": 2,
}

func (x ComparisonOperator) String() string {
	return proto.EnumName(ComparisonOperator_name, int32(x))
}
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type DealsListRequest struct {
	SupplierID       string             `protobuf:"bytes,1,opt,name=supplierID" json:"supplierID,omitempty"`
	ConsumerID       string             `protobuf:"bytes,2,opt,name=consumerID" json:"consumerID,omitempty"`
	MasterID         string             `protobuf:"bytes,3,opt,name=masterID" json:"masterID,omitempty"`
	AskID            string             `protobuf:"bytes,4,opt,name=askID" json:"askID,omitempty"`
	BidID            string             `protobuf:"bytes,5,opt,name=bidID" json:"bidID,omitempty"`
	Duration         uint64             `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
	DurationOperator ComparisonOperator `protobuf:"varint,7,opt,name=durationOperator,enum=sonm.ComparisonOperator" json:"durationOperator,omitempty"`
	Price            string             `protobuf:"bytes,8,opt,name=price" json:"price,omitempty"`
	PriceOperator    ComparisonOperator `protobuf:"varint,9,opt,name=priceOperator,enum=sonm.ComparisonOperator" json:"priceOperator,omitempty"`
	StartTime        *Timestamp         `protobuf:"bytes,10,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime          *Timestamp         `protobuf:"bytes,11,opt,name=EndTime" json:"EndTime,omitempty"`
	Status           MarketDealStatus   `protobuf:"varint,12,opt,name=status,enum=sonm.MarketDealStatus" json:"status,omitempty"`
	TotalPayout      string             `protobuf:"bytes,13,opt,name=totalPayout" json:"totalPayout,omitempty"`
	LastBillTS       *Timestamp         `protobuf:"bytes,14,opt,name=lastBillTS" json:"lastBillTS,omitempty"`
	Limit            uint64             `protobuf:"varint,15,opt,name=limit" json:"limit,omitempty"`
	Offset           uint64             `protobuf:"varint,16,opt,name=offset" json:"offset,omitempty"`
}

func (m *DealsListRequest) Reset()                    { *m = DealsListRequest{} }
func (m *DealsListRequest) String() string            { return proto.CompactTextString(m) }
func (*DealsListRequest) ProtoMessage()               {}
func (*DealsListRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *DealsListRequest) GetSupplierID() string {
	if m != nil {
		return m.SupplierID
	}
	return ""
}

func (m *DealsListRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *DealsListRequest) GetMasterID() string {
	if m != nil {
		return m.MasterID
	}
	return ""
}

func (m *DealsListRequest) GetAskID() string {
	if m != nil {
		return m.AskID
	}
	return ""
}

func (m *DealsListRequest) GetBidID() string {
	if m != nil {
		return m.BidID
	}
	return ""
}

func (m *DealsListRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *DealsListRequest) GetDurationOperator() ComparisonOperator {
	if m != nil {
		return m.DurationOperator
	}
	return ComparisonOperator_EQ
}

func (m *DealsListRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *DealsListRequest) GetPriceOperator() ComparisonOperator {
	if m != nil {
		return m.PriceOperator
	}
	return ComparisonOperator_EQ
}

func (m *DealsListRequest) GetStartTime() *Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *DealsListRequest) GetEndTime() *Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *DealsListRequest) GetStatus() MarketDealStatus {
	if m != nil {
		return m.Status
	}
	return MarketDealStatus_MARKET_STATUS_UNKNOWN
}

func (m *DealsListRequest) GetTotalPayout() string {
	if m != nil {
		return m.TotalPayout
	}
	return ""
}

func (m *DealsListRequest) GetLastBillTS() *Timestamp {
	if m != nil {
		return m.LastBillTS
	}
	return nil
}

func (m *DealsListRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DealsListRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DealsListReply struct {
	Deals []*MarketDeal `protobuf:"bytes,1,rep,name=deals" json:"deals,omitempty"`
}

func (m *DealsListReply) Reset()                    { *m = DealsListReply{} }
func (m *DealsListReply) String() string            { return proto.CompactTextString(m) }
func (*DealsListReply) ProtoMessage()               {}
func (*DealsListReply) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *DealsListReply) GetDeals() []*MarketDeal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type OrdersListRequest struct {
	DealID           string              `protobuf:"bytes,1,opt,name=dealID" json:"dealID,omitempty"`
	Type             MarketOrderType     `protobuf:"varint,2,opt,name=type,enum=sonm.MarketOrderType" json:"type,omitempty"`
	Status           MarketOrderStatus   `protobuf:"varint,3,opt,name=status,enum=sonm.MarketOrderStatus" json:"status,omitempty"`
	AuthorID         string              `protobuf:"bytes,4,opt,name=authorID" json:"authorID,omitempty"`
	CounterpartyID   string              `protobuf:"bytes,5,opt,name=counterpartyID" json:"counterpartyID,omitempty"`
	Duration         uint64              `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
	DurationOperator ComparisonOperator  `protobuf:"varint,7,opt,name=durationOperator,enum=sonm.ComparisonOperator" json:"durationOperator,omitempty"`
	Price            string              `protobuf:"bytes,9,opt,name=price" json:"price,omitempty"`
	PriceOperator    ComparisonOperator  `protobuf:"varint,10,opt,name=priceOperator,enum=sonm.ComparisonOperator" json:"priceOperator,omitempty"`
	Netflags         uint64              `protobuf:"varint,11,opt,name=netflags" json:"netflags,omitempty"`
	IdentityLevel    MarketIdentityLevel `protobuf:"varint,12,opt,name=identityLevel,enum=sonm.MarketIdentityLevel" json:"identityLevel,omitempty"`
	Limit            uint64              `protobuf:"varint,13,opt,name=limit" json:"limit,omitempty"`
	Offset           uint64              `protobuf:"varint,14,opt,name=offset" json:"offset,omitempty"`
}

func (m *OrdersListRequest) Reset()                    { *m = OrdersListRequest{} }
func (m *OrdersListRequest) String() string            { return proto.CompactTextString(m) }
func (*OrdersListRequest) ProtoMessage()               {}
func (*OrdersListRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *OrdersListRequest) GetDealID() string {
	if m != nil {
		return m.DealID
	}
	return ""
}

func (m *OrdersListRequest) GetType() MarketOrderType {
	if m != nil {
		return m.Type
	}
	return MarketOrderType_MARKET_ANY
}

func (m *OrdersListRequest) GetStatus() MarketOrderStatus {
	if m != nil {
		return m.Status
	}
	return MarketOrderStatus_MARKET_ORDER_INACTIVE
}

func (m *OrdersListRequest) GetAuthorID() string {
	if m != nil {
		return m.AuthorID
	}
	return ""
}

func (m *OrdersListRequest) GetCounterpartyID() string {
	if m != nil {
		return m.CounterpartyID
	}
	return ""
}

func (m *OrdersListRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *OrdersListRequest) GetDurationOperator() ComparisonOperator {
	if m != nil {
		return m.DurationOperator
	}
	return ComparisonOperator_EQ
}

func (m *OrdersListRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrdersListRequest) GetPriceOperator() ComparisonOperator {
	if m != nil {
		return m.PriceOperator
	}
	return ComparisonOperator_EQ
}

func (m *OrdersListRequest) GetNetflags() uint64 {
	if m != nil {
		return m.Netflags
	}
	return 0
}

func (m *OrdersListRequest) GetIdentityLevel() MarketIdentityLevel {
	if m != nil {
		return m.IdentityLevel
	}
	return MarketIdentityLevel_MARKET_ANONIMOUS
}

func (m *OrdersListRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OrdersListRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type OrdersListReply struct {
	Orders []*MarketOrder `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *OrdersListReply) Reset()                    { *m = OrdersListReply{} }
func (m *OrdersListReply) String() string            { return proto.CompactTextString(m) }
func (*OrdersListReply) ProtoMessage()               {}
func (*OrdersListReply) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *OrdersListReply) GetOrders() []*MarketOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type DealChangeRequestsReply struct {
	ChangeRequests []*DealChangeRequest `protobuf:"bytes,1,rep,name=changeRequests" json:"changeRequests,omitempty"`
}

func (m *DealChangeRequestsReply) Reset()                    { *m = DealChangeRequestsReply{} }
func (m *DealChangeRequestsReply) String() string            { return proto.CompactTextString(m) }
func (*DealChangeRequestsReply) ProtoMessage()               {}
func (*DealChangeRequestsReply) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *DealChangeRequestsReply) GetChangeRequests() []*DealChangeRequest {
	if m != nil {
		return m.ChangeRequests
	}
	return nil
}

func init() {
	proto.RegisterType((*DealsListRequest)(nil), "sonm.DealsListRequest")
	proto.RegisterType((*DealsListReply)(nil), "sonm.DealsListReply")
	proto.RegisterType((*OrdersListRequest)(nil), "sonm.OrdersListRequest")
	proto.RegisterType((*OrdersListReply)(nil), "sonm.OrdersListReply")
	proto.RegisterType((*DealChangeRequestsReply)(nil), "sonm.DealChangeRequestsReply")
	proto.RegisterEnum("sonm.ComparisonOperator", ComparisonOperator_name, ComparisonOperator_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DWH service

type DWHClient interface {
	GetOrdersList(ctx context.Context, in *OrdersListRequest, opts ...grpc.CallOption) (*OrdersListReply, error)
	GetOrderDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MarketOrder, error)
	GetDealsList(ctx context.Context, in *DealsListRequest, opts ...grpc.CallOption) (*DealsListReply, error)
	GetDealDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MarketDeal, error)
	GetDealChangeRequests(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DealChangeRequestsReply, error)
}

type dWHClient struct {
	cc *grpc.ClientConn
}

func NewDWHClient(cc *grpc.ClientConn) DWHClient {
	return &dWHClient{cc}
}

func (c *dWHClient) GetOrdersList(ctx context.Context, in *OrdersListRequest, opts ...grpc.CallOption) (*OrdersListReply, error) {
	out := new(OrdersListReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetOrdersList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetOrderDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MarketOrder, error) {
	out := new(MarketOrder)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetOrderDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealsList(ctx context.Context, in *DealsListRequest, opts ...grpc.CallOption) (*DealsListReply, error) {
	out := new(DealsListReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealsList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealDetails(ctx context.Context, in *ID, opts ...grpc.CallOption) (*MarketDeal, error) {
	out := new(MarketDeal)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dWHClient) GetDealChangeRequests(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DealChangeRequestsReply, error) {
	out := new(DealChangeRequestsReply)
	err := grpc.Invoke(ctx, "/sonm.DWH/GetDealChangeRequests", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DWH service

type DWHServer interface {
	GetOrdersList(context.Context, *OrdersListRequest) (*OrdersListReply, error)
	GetOrderDetails(context.Context, *ID) (*MarketOrder, error)
	GetDealsList(context.Context, *DealsListRequest) (*DealsListReply, error)
	GetDealDetails(context.Context, *ID) (*MarketDeal, error)
	GetDealChangeRequests(context.Context, *ID) (*DealChangeRequestsReply, error)
}

func RegisterDWHServer(s *grpc.Server, srv DWHServer) {
	s.RegisterService(&_DWH_serviceDesc, srv)
}

func _DWH_GetOrdersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetOrdersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetOrdersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetOrdersList(ctx, req.(*OrdersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetOrderDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetOrderDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetOrderDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetOrderDetails(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealsList(ctx, req.(*DealsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealDetails(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DWH_GetDealChangeRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DWHServer).GetDealChangeRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DWH/GetDealChangeRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DWHServer).GetDealChangeRequests(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _DWH_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.DWH",
	HandlerType: (*DWHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrdersList",
			Handler:    _DWH_GetOrdersList_Handler,
		},
		{
			MethodName: "GetOrderDetails",
			Handler:    _DWH_GetOrderDetails_Handler,
		},
		{
			MethodName: "GetDealsList",
			Handler:    _DWH_GetDealsList_Handler,
		},
		{
			MethodName: "GetDealDetails",
			Handler:    _DWH_GetDealDetails_Handler,
		},
		{
			MethodName: "GetDealChangeRequests",
			Handler:    _DWH_GetDealChangeRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dwh.proto",
}

// Begin grpccmd
var _ = grpccmd.RunE

// DWH
var _DWHCmd = &cobra.Command{
	Use:   "dWH [method]",
	Short: "Subcommand for the DWH service.",
}

var _DWH_GetOrdersListCmd = &cobra.Command{
	Use:   "getOrdersList",
	Short: "Make the GetOrdersList method call, input-type: sonm.OrdersListRequest output-type: sonm.OrdersListReply",
	RunE: grpccmd.RunE(
		"GetOrdersList",
		"sonm.OrdersListRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetOrdersListCmd_gen = &cobra.Command{
	Use:   "getOrdersList-gen",
	Short: "Generate JSON for method call of GetOrdersList (input-type: sonm.OrdersListRequest)",
	RunE:  grpccmd.TypeToJson("sonm.OrdersListRequest"),
}

var _DWH_GetOrderDetailsCmd = &cobra.Command{
	Use:   "getOrderDetails",
	Short: "Make the GetOrderDetails method call, input-type: sonm.ID output-type: sonm.MarketOrder",
	RunE: grpccmd.RunE(
		"GetOrderDetails",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetOrderDetailsCmd_gen = &cobra.Command{
	Use:   "getOrderDetails-gen",
	Short: "Generate JSON for method call of GetOrderDetails (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _DWH_GetDealsListCmd = &cobra.Command{
	Use:   "getDealsList",
	Short: "Make the GetDealsList method call, input-type: sonm.DealsListRequest output-type: sonm.DealsListReply",
	RunE: grpccmd.RunE(
		"GetDealsList",
		"sonm.DealsListRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealsListCmd_gen = &cobra.Command{
	Use:   "getDealsList-gen",
	Short: "Generate JSON for method call of GetDealsList (input-type: sonm.DealsListRequest)",
	RunE:  grpccmd.TypeToJson("sonm.DealsListRequest"),
}

var _DWH_GetDealDetailsCmd = &cobra.Command{
	Use:   "getDealDetails",
	Short: "Make the GetDealDetails method call, input-type: sonm.ID output-type: sonm.MarketDeal",
	RunE: grpccmd.RunE(
		"GetDealDetails",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealDetailsCmd_gen = &cobra.Command{
	Use:   "getDealDetails-gen",
	Short: "Generate JSON for method call of GetDealDetails (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _DWH_GetDealChangeRequestsCmd = &cobra.Command{
	Use:   "getDealChangeRequests",
	Short: "Make the GetDealChangeRequests method call, input-type: sonm.ID output-type: sonm.DealChangeRequestsReply",
	RunE: grpccmd.RunE(
		"GetDealChangeRequests",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewDWHClient(cc)
		},
	),
}

var _DWH_GetDealChangeRequestsCmd_gen = &cobra.Command{
	Use:   "getDealChangeRequests-gen",
	Short: "Generate JSON for method call of GetDealChangeRequests (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

// Register commands with the root command and service command
func init() {
	grpccmd.RegisterServiceCmd(_DWHCmd)
	_DWHCmd.AddCommand(
		_DWH_GetOrdersListCmd,
		_DWH_GetOrdersListCmd_gen,
		_DWH_GetOrderDetailsCmd,
		_DWH_GetOrderDetailsCmd_gen,
		_DWH_GetDealsListCmd,
		_DWH_GetDealsListCmd_gen,
		_DWH_GetDealDetailsCmd,
		_DWH_GetDealDetailsCmd_gen,
		_DWH_GetDealChangeRequestsCmd,
		_DWH_GetDealChangeRequestsCmd_gen,
	)
}

// End grpccmd

func init() { proto.RegisterFile("dwh.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xee, 0xdf, 0xba, 0xf6, 0x74, 0x4d, 0x3b, 0x6b, 0xeb, 0x4c, 0x25, 0x50, 0xd5, 0x8b, 0xa9,
	0x43, 0xa2, 0x43, 0xe5, 0x86, 0x0b, 0xb4, 0x89, 0x2d, 0xd5, 0xa8, 0x34, 0x34, 0xc8, 0x2a, 0x21,
	0x71, 0xe7, 0xb5, 0xde, 0x66, 0x2d, 0x7f, 0xd8, 0x0e, 0x28, 0x2f, 0xc1, 0xa3, 0xf0, 0x46, 0xbc,
	0x0b, 0x8a, 0xed, 0xa6, 0x49, 0x33, 0x40, 0xdc, 0x70, 0xe7, 0xef, 0xc7, 0xe7, 0xf4, 0x1c, 0x7f,
	0x51, 0xa1, 0xb9, 0xfc, 0x76, 0x3f, 0x0e, 0x79, 0x20, 0x03, 0x54, 0x13, 0x81, 0xef, 0xf5, 0x77,
	0x3d, 0xc2, 0x1f, 0xa8, 0x0c, 0x5d, 0xb2, 0xa0, 0x5a, 0xe8, 0x77, 0x98, 0x9f, 0x48, 0x3e, 0x23,
	0x2b, 0x42, 0x32, 0x8f, 0x0a, 0x49, 0xbc, 0x50, 0x13, 0xc3, 0x9f, 0x35, 0xe8, 0xda, 0x94, 0xb8,
	0xe2, 0x92, 0x09, 0xe9, 0xd0, 0x2f, 0x11, 0x15, 0x12, 0x3d, 0x03, 0x10, 0x51, 0x18, 0xba, 0x8c,
	0xf2, 0x99, 0x8d, 0xcb, 0x83, 0xf2, 0xa8, 0xe9, 0x64, 0x98, 0x44, 0x5f, 0x04, 0xbe, 0x88, 0x3c,
	0xa5, 0x57, 0xb4, 0xbe, 0x66, 0x50, 0x1f, 0x1a, 0x1e, 0x11, 0x52, 0xa9, 0x55, 0xa5, 0xa6, 0x18,
	0xed, 0xc1, 0x16, 0x11, 0x0f, 0x33, 0x1b, 0xd7, 0x94, 0xa0, 0x41, 0xc2, 0xde, 0xb0, 0xe5, 0xcc,
	0xc6, 0x5b, 0x9a, 0x55, 0x20, 0xa9, 0xb3, 0x8c, 0x38, 0x91, 0x2c, 0xf0, 0x71, 0x7d, 0x50, 0x1e,
	0xd5, 0x9c, 0x14, 0x23, 0x1b, 0xba, 0xab, 0xf3, 0x55, 0x48, 0x39, 0x91, 0x01, 0xc7, 0xdb, 0x83,
	0xf2, 0xc8, 0x9a, 0xe0, 0x71, 0x32, 0xf3, 0xf8, 0x3c, 0xf0, 0x42, 0xc2, 0x99, 0x58, 0xeb, 0x4e,
	0xe1, 0x46, 0xd2, 0x37, 0xe4, 0x6c, 0x41, 0x71, 0x43, 0xf7, 0x55, 0x00, 0x9d, 0x40, 0x5b, 0x1d,
	0xd2, 0xc2, 0xcd, 0xbf, 0x14, 0xce, 0xdb, 0xd1, 0x0b, 0x68, 0x5e, 0x4b, 0xc2, 0xe5, 0x9c, 0x79,
	0x14, 0xc3, 0xa0, 0x3c, 0x6a, 0x4d, 0x3a, 0xfa, 0xee, 0x7c, 0xb5, 0x7e, 0x67, 0xed, 0x40, 0x47,
	0xb0, 0x3d, 0xf5, 0x97, 0xca, 0xdc, 0x7a, 0xdc, 0xbc, 0xd2, 0xd1, 0x18, 0xea, 0x42, 0x12, 0x19,
	0x09, 0xbc, 0xa3, 0x7e, 0x52, 0x4f, 0x3b, 0xdf, 0xab, 0x97, 0x4f, 0xde, 0xf1, 0x5a, 0xa9, 0x8e,
	0x71, 0xa1, 0x01, 0xb4, 0x64, 0x20, 0x89, 0xfb, 0x81, 0xc4, 0x41, 0x24, 0x71, 0x5b, 0x4d, 0x99,
	0xa5, 0xd0, 0x31, 0x80, 0x4b, 0x84, 0x3c, 0x63, 0xae, 0x3b, 0xbf, 0xc6, 0xd6, 0xe3, 0xfd, 0x33,
	0x96, 0x64, 0x65, 0x2e, 0xf3, 0x98, 0xc4, 0x1d, 0xf5, 0x22, 0x1a, 0xa0, 0x1e, 0xd4, 0x83, 0xdb,
	0x5b, 0x41, 0x25, 0xee, 0x2a, 0xda, 0xa0, 0xe1, 0x6b, 0xb0, 0x32, 0xf1, 0x0a, 0xdd, 0x18, 0x1d,
	0xc2, 0xd6, 0x32, 0x61, 0x70, 0x79, 0x50, 0x1d, 0xb5, 0x26, 0xdd, 0xcd, 0x09, 0x1c, 0x2d, 0x0f,
	0xbf, 0xd7, 0x60, 0xf7, 0x8a, 0x2f, 0x29, 0xcf, 0x45, 0xb3, 0x07, 0xf5, 0x44, 0x4e, 0x63, 0x69,
	0x10, 0x3a, 0x82, 0x9a, 0x8c, 0x43, 0xaa, 0xc2, 0x68, 0x4d, 0xf6, 0xb3, 0x45, 0x55, 0x91, 0x79,
	0x1c, 0x52, 0x47, 0x59, 0xd0, 0x71, 0xba, 0xc3, 0xaa, 0x32, 0x1f, 0x14, 0xcc, 0x1b, 0x4b, 0xec,
	0x43, 0x83, 0x44, 0xf2, 0x3e, 0xe0, 0x69, 0x6a, 0x53, 0x8c, 0x0e, 0xc1, 0x5a, 0x04, 0x91, 0x2f,
	0x29, 0x0f, 0x09, 0x97, 0x71, 0x9a, 0xe0, 0x0d, 0xf6, 0x7f, 0x46, 0xb9, 0xf9, 0xc7, 0x28, 0xc3,
	0xbf, 0x45, 0xb9, 0x0f, 0x0d, 0x9f, 0xca, 0x5b, 0x97, 0xdc, 0x09, 0x15, 0xce, 0x9a, 0x93, 0x62,
	0x74, 0x0a, 0x6d, 0xb6, 0xa4, 0xbe, 0x64, 0x32, 0xbe, 0xa4, 0x5f, 0xa9, 0x6b, 0x32, 0xf9, 0x24,
	0xbb, 0xcf, 0x59, 0xd6, 0xe0, 0xe4, 0xfd, 0xeb, 0x28, 0xb5, 0x1f, 0x8f, 0x92, 0x95, 0x8b, 0xd2,
	0x1b, 0xe8, 0x64, 0xf3, 0x90, 0x64, 0xe9, 0x08, 0xea, 0x81, 0xa2, 0x4c, 0x98, 0x76, 0x0b, 0x4f,
	0xe9, 0x18, 0xc3, 0xf0, 0x33, 0x1c, 0x24, 0xe9, 0x3a, 0xbf, 0x27, 0xfe, 0x1d, 0x35, 0x69, 0x12,
	0xba, 0xca, 0x29, 0x58, 0x8b, 0x1c, 0x6d, 0xaa, 0x99, 0x60, 0x14, 0xae, 0x39, 0x1b, 0xf6, 0xe7,
	0x63, 0x40, 0xc5, 0x4d, 0xa2, 0x3a, 0x54, 0xa6, 0x1f, 0xbb, 0x25, 0xb4, 0x0d, 0xd5, 0x8b, 0xf9,
	0xb4, 0x5b, 0x4e, 0x0e, 0x97, 0xf3, 0x69, 0xb7, 0x32, 0xf9, 0x51, 0x81, 0xaa, 0xfd, 0xe9, 0x1d,
	0x7a, 0x0b, 0xed, 0x0b, 0xf3, 0x3b, 0xd5, 0x50, 0xc8, 0x74, 0x2c, 0xc4, 0xbe, 0xbf, 0x5f, 0x14,
	0x42, 0x37, 0x1e, 0x96, 0xd0, 0x4b, 0xe8, 0xac, 0x4a, 0xd8, 0x54, 0x12, 0xe6, 0x0a, 0xd4, 0xd0,
	0xde, 0x99, 0xdd, 0x2f, 0xae, 0x63, 0x58, 0x42, 0x27, 0xb0, 0x73, 0xa1, 0xbf, 0x34, 0xdd, 0xb3,
	0xb7, 0x9e, 0x32, 0xd7, 0x72, 0xaf, 0xc0, 0xeb, 0x8e, 0x63, 0xb0, 0xcc, 0xfd, 0x62, 0xc3, 0xc2,
	0xc7, 0x3c, 0x2c, 0xa1, 0x33, 0xd8, 0x37, 0xfe, 0xfc, 0xee, 0x33, 0xd7, 0x9e, 0xfe, 0x66, 0xd1,
	0xc2, 0xf4, 0xbc, 0xa9, 0xab, 0x3f, 0xab, 0x57, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xae,
	0xc9, 0x42, 0xf4, 0x06, 0x00, 0x00,
}
