// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marketplace.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// grpccmd imports
import (
	"io"

	"github.com/spf13/cobra"
	"github.com/sshaman1101/grpccmd"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MarketOrderType int32

const (
	MarketOrderType_MARKET_ANY MarketOrderType = 0
	MarketOrderType_MARKET_BID MarketOrderType = 1
	MarketOrderType_MARKET_ASK MarketOrderType = 2
)

var MarketOrderType_name = map[int32]string{
	0: "MARKET_ANY",
	1: "MARKET_BID",
	2: "MARKET_ASK",
}
var MarketOrderType_value = map[string]int32{
	"MARKET_ANY": 0,
	"MARKET_BID": 1,
	"MARKET_ASK": 2,
}

func (x MarketOrderType) String() string {
	return proto.EnumName(MarketOrderType_name, int32(x))
}
func (MarketOrderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

type MarketOrderStatus int32

const (
	MarketOrderStatus_MARKET_ORDER_INACTIVE MarketOrderStatus = 0
	MarketOrderStatus_MARKET_ORDER_ACTIVE   MarketOrderStatus = 1
)

var MarketOrderStatus_name = map[int32]string{
	0: "MARKET_ORDER_INACTIVE",
	1: "MARKET_ORDER_ACTIVE",
}
var MarketOrderStatus_value = map[string]int32{
	"MARKET_ORDER_INACTIVE": 0,
	"MARKET_ORDER_ACTIVE":   1,
}

func (x MarketOrderStatus) String() string {
	return proto.EnumName(MarketOrderStatus_name, int32(x))
}
func (MarketOrderStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

type MarketIdentityLevel int32

const (
	MarketIdentityLevel_MARKET_ANONIMOUS    MarketIdentityLevel = 0
	MarketIdentityLevel_MARKET_PSEUDONYMOUS MarketIdentityLevel = 1
	MarketIdentityLevel_MARKET_IDENTIFIED   MarketIdentityLevel = 2
)

var MarketIdentityLevel_name = map[int32]string{
	0: "MARKET_ANONIMOUS",
	1: "MARKET_PSEUDONYMOUS",
	2: "MARKET_IDENTIFIED",
}
var MarketIdentityLevel_value = map[string]int32{
	"MARKET_ANONIMOUS":    0,
	"MARKET_PSEUDONYMOUS": 1,
	"MARKET_IDENTIFIED":   2,
}

func (x MarketIdentityLevel) String() string {
	return proto.EnumName(MarketIdentityLevel_name, int32(x))
}
func (MarketIdentityLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

type MarketDealStatus int32

const (
	MarketDealStatus_MARKET_STATUS_UNKNOWN  MarketDealStatus = 0
	MarketDealStatus_MARKET_STATUS_ACCEPTED MarketDealStatus = 1
	MarketDealStatus_MARKET_STATUS_CLOSED   MarketDealStatus = 2
)

var MarketDealStatus_name = map[int32]string{
	0: "MARKET_STATUS_UNKNOWN",
	1: "MARKET_STATUS_ACCEPTED",
	2: "MARKET_STATUS_CLOSED",
}
var MarketDealStatus_value = map[string]int32{
	"MARKET_STATUS_UNKNOWN":  0,
	"MARKET_STATUS_ACCEPTED": 1,
	"MARKET_STATUS_CLOSED":   2,
}

func (x MarketDealStatus) String() string {
	return proto.EnumName(MarketDealStatus_name, int32(x))
}
func (MarketDealStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

type MarketChangeRequestStatus int32

const (
	MarketChangeRequestStatus_REQUEST_UNKNOWN  MarketChangeRequestStatus = 0
	MarketChangeRequestStatus_REQUEST_CREATED  MarketChangeRequestStatus = 1
	MarketChangeRequestStatus_REQUEST_CANCELED MarketChangeRequestStatus = 2
	MarketChangeRequestStatus_REQUEST_REJECTED MarketChangeRequestStatus = 3
	MarketChangeRequestStatus_REQUEST_ACCEPTED MarketChangeRequestStatus = 4
)

var MarketChangeRequestStatus_name = map[int32]string{
	0: "REQUEST_UNKNOWN",
	1: "REQUEST_CREATED",
	2: "REQUEST_CANCELED",
	3: "REQUEST_REJECTED",
	4: "REQUEST_ACCEPTED",
}
var MarketChangeRequestStatus_value = map[string]int32{
	"REQUEST_UNKNOWN":  0,
	"REQUEST_CREATED":  1,
	"REQUEST_CANCELED": 2,
	"REQUEST_REJECTED": 3,
	"REQUEST_ACCEPTED": 4,
}

func (x MarketChangeRequestStatus) String() string {
	return proto.EnumName(MarketChangeRequestStatus_name, int32(x))
}
func (MarketChangeRequestStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

type GetOrdersRequest struct {
	// Order keeps slot and type for searching
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	// Count describe how namy results must be returned (order by price)
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *GetOrdersRequest) Reset()                    { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()               {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *GetOrdersRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetOrdersRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetOrdersReply struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *GetOrdersReply) Reset()                    { *m = GetOrdersReply{} }
func (m *GetOrdersReply) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersReply) ProtoMessage()               {}
func (*GetOrdersReply) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *GetOrdersReply) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// GetProcessingReply represent Node's local
// orders processing status
type GetProcessingReply struct {
	Orders map[string]*GetProcessingReply_ProcessedOrder `protobuf:"bytes,2,rep,name=orders" json:"orders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetProcessingReply) Reset()                    { *m = GetProcessingReply{} }
func (m *GetProcessingReply) String() string            { return proto.CompactTextString(m) }
func (*GetProcessingReply) ProtoMessage()               {}
func (*GetProcessingReply) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *GetProcessingReply) GetOrders() map[string]*GetProcessingReply_ProcessedOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetProcessingReply_ProcessedOrder struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status    uint32     `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Timestamp *Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Extra     string     `protobuf:"bytes,4,opt,name=extra" json:"extra,omitempty"`
}

func (m *GetProcessingReply_ProcessedOrder) Reset()         { *m = GetProcessingReply_ProcessedOrder{} }
func (m *GetProcessingReply_ProcessedOrder) String() string { return proto.CompactTextString(m) }
func (*GetProcessingReply_ProcessedOrder) ProtoMessage()    {}
func (*GetProcessingReply_ProcessedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor9, []int{2, 0}
}

func (m *GetProcessingReply_ProcessedOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProcessingReply_ProcessedOrder) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProcessingReply_ProcessedOrder) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetProcessingReply_ProcessedOrder) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type TouchOrdersRequest struct {
	IDs []string `protobuf:"bytes,1,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *TouchOrdersRequest) Reset()                    { *m = TouchOrdersRequest{} }
func (m *TouchOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*TouchOrdersRequest) ProtoMessage()               {}
func (*TouchOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *TouchOrdersRequest) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type MarketDeal struct {
	Id             string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Benchmarks     []uint64         `protobuf:"varint,2,rep,packed,name=benchmarks" json:"benchmarks,omitempty"`
	SupplierID     string           `protobuf:"bytes,3,opt,name=supplierID" json:"supplierID,omitempty"`
	ConsumerID     string           `protobuf:"bytes,4,opt,name=consumerID" json:"consumerID,omitempty"`
	MasterID       string           `protobuf:"bytes,5,opt,name=masterID" json:"masterID,omitempty"`
	AskID          string           `protobuf:"bytes,6,opt,name=askID" json:"askID,omitempty"`
	BidID          string           `protobuf:"bytes,7,opt,name=bidID" json:"bidID,omitempty"`
	Duration       uint64           `protobuf:"varint,8,opt,name=duration" json:"duration,omitempty"`
	Price          *BigInt          `protobuf:"bytes,9,opt,name=price" json:"price,omitempty"`
	StartTime      *Timestamp       `protobuf:"bytes,10,opt,name=startTime" json:"startTime,omitempty"`
	EndTime        *Timestamp       `protobuf:"bytes,11,opt,name=endTime" json:"endTime,omitempty"`
	Status         MarketDealStatus `protobuf:"varint,12,opt,name=status,enum=sonm.MarketDealStatus" json:"status,omitempty"`
	BlockedBalance *BigInt          `protobuf:"bytes,13,opt,name=blockedBalance" json:"blockedBalance,omitempty"`
	TotalPayout    *BigInt          `protobuf:"bytes,14,opt,name=totalPayout" json:"totalPayout,omitempty"`
	LastBillTS     *Timestamp       `protobuf:"bytes,15,opt,name=lastBillTS" json:"lastBillTS,omitempty"`
}

func (m *MarketDeal) Reset()                    { *m = MarketDeal{} }
func (m *MarketDeal) String() string            { return proto.CompactTextString(m) }
func (*MarketDeal) ProtoMessage()               {}
func (*MarketDeal) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *MarketDeal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MarketDeal) GetBenchmarks() []uint64 {
	if m != nil {
		return m.Benchmarks
	}
	return nil
}

func (m *MarketDeal) GetSupplierID() string {
	if m != nil {
		return m.SupplierID
	}
	return ""
}

func (m *MarketDeal) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *MarketDeal) GetMasterID() string {
	if m != nil {
		return m.MasterID
	}
	return ""
}

func (m *MarketDeal) GetAskID() string {
	if m != nil {
		return m.AskID
	}
	return ""
}

func (m *MarketDeal) GetBidID() string {
	if m != nil {
		return m.BidID
	}
	return ""
}

func (m *MarketDeal) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MarketDeal) GetPrice() *BigInt {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *MarketDeal) GetStartTime() *Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MarketDeal) GetEndTime() *Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *MarketDeal) GetStatus() MarketDealStatus {
	if m != nil {
		return m.Status
	}
	return MarketDealStatus_MARKET_STATUS_UNKNOWN
}

func (m *MarketDeal) GetBlockedBalance() *BigInt {
	if m != nil {
		return m.BlockedBalance
	}
	return nil
}

func (m *MarketDeal) GetTotalPayout() *BigInt {
	if m != nil {
		return m.TotalPayout
	}
	return nil
}

func (m *MarketDeal) GetLastBillTS() *Timestamp {
	if m != nil {
		return m.LastBillTS
	}
	return nil
}

type MarketOrder struct {
	Id            string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DealID        string              `protobuf:"bytes,2,opt,name=dealID" json:"dealID,omitempty"`
	OrderType     MarketOrderType     `protobuf:"varint,3,opt,name=orderType,enum=sonm.MarketOrderType" json:"orderType,omitempty"`
	OrderStatus   MarketOrderStatus   `protobuf:"varint,4,opt,name=orderStatus,enum=sonm.MarketOrderStatus" json:"orderStatus,omitempty"`
	Author        string              `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	Counterparty  string              `protobuf:"bytes,6,opt,name=counterparty" json:"counterparty,omitempty"`
	Price         *BigInt             `protobuf:"bytes,7,opt,name=price" json:"price,omitempty"`
	Duration      uint64              `protobuf:"varint,8,opt,name=duration" json:"duration,omitempty"`
	Netflags      []bool              `protobuf:"varint,9,rep,packed,name=netflags" json:"netflags,omitempty"`
	IdentityLevel MarketIdentityLevel `protobuf:"varint,10,opt,name=identityLevel,enum=sonm.MarketIdentityLevel" json:"identityLevel,omitempty"`
	Blacklist     string              `protobuf:"bytes,11,opt,name=blacklist" json:"blacklist,omitempty"`
	Tag           []byte              `protobuf:"bytes,12,opt,name=tag,proto3" json:"tag,omitempty"`
	Benchmarks    []uint64            `protobuf:"varint,13,rep,packed,name=benchmarks" json:"benchmarks,omitempty"`
	FrozenSum     *BigInt             `protobuf:"bytes,14,opt,name=frozenSum" json:"frozenSum,omitempty"`
}

func (m *MarketOrder) Reset()                    { *m = MarketOrder{} }
func (m *MarketOrder) String() string            { return proto.CompactTextString(m) }
func (*MarketOrder) ProtoMessage()               {}
func (*MarketOrder) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

func (m *MarketOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MarketOrder) GetDealID() string {
	if m != nil {
		return m.DealID
	}
	return ""
}

func (m *MarketOrder) GetOrderType() MarketOrderType {
	if m != nil {
		return m.OrderType
	}
	return MarketOrderType_MARKET_ANY
}

func (m *MarketOrder) GetOrderStatus() MarketOrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return MarketOrderStatus_MARKET_ORDER_INACTIVE
}

func (m *MarketOrder) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *MarketOrder) GetCounterparty() string {
	if m != nil {
		return m.Counterparty
	}
	return ""
}

func (m *MarketOrder) GetPrice() *BigInt {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *MarketOrder) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MarketOrder) GetNetflags() []bool {
	if m != nil {
		return m.Netflags
	}
	return nil
}

func (m *MarketOrder) GetIdentityLevel() MarketIdentityLevel {
	if m != nil {
		return m.IdentityLevel
	}
	return MarketIdentityLevel_MARKET_ANONIMOUS
}

func (m *MarketOrder) GetBlacklist() string {
	if m != nil {
		return m.Blacklist
	}
	return ""
}

func (m *MarketOrder) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *MarketOrder) GetBenchmarks() []uint64 {
	if m != nil {
		return m.Benchmarks
	}
	return nil
}

func (m *MarketOrder) GetFrozenSum() *BigInt {
	if m != nil {
		return m.FrozenSum
	}
	return nil
}

type DealChangeRequest struct {
	Id          string                    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DealID      string                    `protobuf:"bytes,2,opt,name=dealID" json:"dealID,omitempty"`
	RequestType MarketOrderType           `protobuf:"varint,3,opt,name=requestType,enum=sonm.MarketOrderType" json:"requestType,omitempty"`
	Duration    uint64                    `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	Price       *BigInt                   `protobuf:"bytes,5,opt,name=price" json:"price,omitempty"`
	Status      MarketChangeRequestStatus `protobuf:"varint,6,opt,name=status,enum=sonm.MarketChangeRequestStatus" json:"status,omitempty"`
}

func (m *DealChangeRequest) Reset()                    { *m = DealChangeRequest{} }
func (m *DealChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*DealChangeRequest) ProtoMessage()               {}
func (*DealChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *DealChangeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DealChangeRequest) GetDealID() string {
	if m != nil {
		return m.DealID
	}
	return ""
}

func (m *DealChangeRequest) GetRequestType() MarketOrderType {
	if m != nil {
		return m.RequestType
	}
	return MarketOrderType_MARKET_ANY
}

func (m *DealChangeRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *DealChangeRequest) GetPrice() *BigInt {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *DealChangeRequest) GetStatus() MarketChangeRequestStatus {
	if m != nil {
		return m.Status
	}
	return MarketChangeRequestStatus_REQUEST_UNKNOWN
}

func init() {
	proto.RegisterType((*GetOrdersRequest)(nil), "sonm.GetOrdersRequest")
	proto.RegisterType((*GetOrdersReply)(nil), "sonm.GetOrdersReply")
	proto.RegisterType((*GetProcessingReply)(nil), "sonm.GetProcessingReply")
	proto.RegisterType((*GetProcessingReply_ProcessedOrder)(nil), "sonm.GetProcessingReply.ProcessedOrder")
	proto.RegisterType((*TouchOrdersRequest)(nil), "sonm.TouchOrdersRequest")
	proto.RegisterType((*MarketDeal)(nil), "sonm.MarketDeal")
	proto.RegisterType((*MarketOrder)(nil), "sonm.MarketOrder")
	proto.RegisterType((*DealChangeRequest)(nil), "sonm.DealChangeRequest")
	proto.RegisterEnum("sonm.MarketOrderType", MarketOrderType_name, MarketOrderType_value)
	proto.RegisterEnum("sonm.MarketOrderStatus", MarketOrderStatus_name, MarketOrderStatus_value)
	proto.RegisterEnum("sonm.MarketIdentityLevel", MarketIdentityLevel_name, MarketIdentityLevel_value)
	proto.RegisterEnum("sonm.MarketDealStatus", MarketDealStatus_name, MarketDealStatus_value)
	proto.RegisterEnum("sonm.MarketChangeRequestStatus", MarketChangeRequestStatus_name, MarketChangeRequestStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Market service

type MarketClient interface {
	// GetOrders returns orders by given filter parameters.
	// Note that set of filters may be changed in the closest future.
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error)
	// CreateOrder places new order on the Marketplace.
	// Note that current impl of Node API prevents you from
	// creating ASKs orders.
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	// GetOrderByID returns order by given ID.
	// If order save an `inactive` status returns error instead.
	GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error)
	// CancelOrder removes active order from the Marketplace.
	// todo(sshaman1101): use `ID` as parameter instead of whole `Order` struct.
	CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error)
	// GetProcessing returns currently processing orders.
	// todo: rethink and improve.
	GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error)
	// todo: remove
	TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error)
}

type marketClient struct {
	cc *grpc.ClientConn
}

func NewMarketClient(cc *grpc.ClientConn) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error) {
	out := new(GetOrdersReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrderByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error) {
	out := new(GetProcessingReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetProcessing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/TouchOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Market service

type MarketServer interface {
	// GetOrders returns orders by given filter parameters.
	// Note that set of filters may be changed in the closest future.
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersReply, error)
	// CreateOrder places new order on the Marketplace.
	// Note that current impl of Node API prevents you from
	// creating ASKs orders.
	CreateOrder(context.Context, *Order) (*Order, error)
	// GetOrderByID returns order by given ID.
	// If order save an `inactive` status returns error instead.
	GetOrderByID(context.Context, *ID) (*Order, error)
	// CancelOrder removes active order from the Marketplace.
	// todo(sshaman1101): use `ID` as parameter instead of whole `Order` struct.
	CancelOrder(context.Context, *Order) (*Empty, error)
	// GetProcessing returns currently processing orders.
	// todo: rethink and improve.
	GetProcessing(context.Context, *Empty) (*GetProcessingReply, error)
	// todo: remove
	TouchOrders(context.Context, *TouchOrdersRequest) (*Empty, error)
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrderByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CancelOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetProcessing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_TouchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).TouchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/TouchOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).TouchOrders(ctx, req.(*TouchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrders",
			Handler:    _Market_GetOrders_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Market_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrderByID",
			Handler:    _Market_GetOrderByID_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Market_CancelOrder_Handler,
		},
		{
			MethodName: "GetProcessing",
			Handler:    _Market_GetProcessing_Handler,
		},
		{
			MethodName: "TouchOrders",
			Handler:    _Market_TouchOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace.proto",
}

// Begin grpccmd
var _ = grpccmd.RunE

// Market
var _MarketCmd = &cobra.Command{
	Use:   "market [method]",
	Short: "Subcommand for the Market service.",
}

var _Market_GetOrdersCmd = &cobra.Command{
	Use:   "getOrders",
	Short: "Make the GetOrders method call, input-type: sonm.GetOrdersRequest output-type: sonm.GetOrdersReply",
	RunE: grpccmd.RunE(
		"GetOrders",
		"sonm.GetOrdersRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetOrdersCmd_gen = &cobra.Command{
	Use:   "getOrders-gen",
	Short: "Generate JSON for method call of GetOrders (input-type: sonm.GetOrdersRequest)",
	RunE:  grpccmd.TypeToJson("sonm.GetOrdersRequest"),
}

var _Market_CreateOrderCmd = &cobra.Command{
	Use:   "createOrder",
	Short: "Make the CreateOrder method call, input-type: sonm.Order output-type: sonm.Order",
	RunE: grpccmd.RunE(
		"CreateOrder",
		"sonm.Order",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_CreateOrderCmd_gen = &cobra.Command{
	Use:   "createOrder-gen",
	Short: "Generate JSON for method call of CreateOrder (input-type: sonm.Order)",
	RunE:  grpccmd.TypeToJson("sonm.Order"),
}

var _Market_GetOrderByIDCmd = &cobra.Command{
	Use:   "getOrderByID",
	Short: "Make the GetOrderByID method call, input-type: sonm.ID output-type: sonm.Order",
	RunE: grpccmd.RunE(
		"GetOrderByID",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetOrderByIDCmd_gen = &cobra.Command{
	Use:   "getOrderByID-gen",
	Short: "Generate JSON for method call of GetOrderByID (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _Market_CancelOrderCmd = &cobra.Command{
	Use:   "cancelOrder",
	Short: "Make the CancelOrder method call, input-type: sonm.Order output-type: sonm.Empty",
	RunE: grpccmd.RunE(
		"CancelOrder",
		"sonm.Order",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_CancelOrderCmd_gen = &cobra.Command{
	Use:   "cancelOrder-gen",
	Short: "Generate JSON for method call of CancelOrder (input-type: sonm.Order)",
	RunE:  grpccmd.TypeToJson("sonm.Order"),
}

var _Market_GetProcessingCmd = &cobra.Command{
	Use:   "getProcessing",
	Short: "Make the GetProcessing method call, input-type: sonm.Empty output-type: sonm.GetProcessingReply",
	RunE: grpccmd.RunE(
		"GetProcessing",
		"sonm.Empty",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_GetProcessingCmd_gen = &cobra.Command{
	Use:   "getProcessing-gen",
	Short: "Generate JSON for method call of GetProcessing (input-type: sonm.Empty)",
	RunE:  grpccmd.TypeToJson("sonm.Empty"),
}

var _Market_TouchOrdersCmd = &cobra.Command{
	Use:   "touchOrders",
	Short: "Make the TouchOrders method call, input-type: sonm.TouchOrdersRequest output-type: sonm.Empty",
	RunE: grpccmd.RunE(
		"TouchOrders",
		"sonm.TouchOrdersRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewMarketClient(cc)
		},
	),
}

var _Market_TouchOrdersCmd_gen = &cobra.Command{
	Use:   "touchOrders-gen",
	Short: "Generate JSON for method call of TouchOrders (input-type: sonm.TouchOrdersRequest)",
	RunE:  grpccmd.TypeToJson("sonm.TouchOrdersRequest"),
}

// Register commands with the root command and service command
func init() {
	grpccmd.RegisterServiceCmd(_MarketCmd)
	_MarketCmd.AddCommand(
		_Market_GetOrdersCmd,
		_Market_GetOrdersCmd_gen,
		_Market_CreateOrderCmd,
		_Market_CreateOrderCmd_gen,
		_Market_GetOrderByIDCmd,
		_Market_GetOrderByIDCmd_gen,
		_Market_CancelOrderCmd,
		_Market_CancelOrderCmd_gen,
		_Market_GetProcessingCmd,
		_Market_GetProcessingCmd_gen,
		_Market_TouchOrdersCmd,
		_Market_TouchOrdersCmd_gen,
	)
}

// End grpccmd

func init() { proto.RegisterFile("marketplace.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 1100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xce, 0x7f, 0xeb, 0x93, 0x34, 0x75, 0xa7, 0x3f, 0xeb, 0x46, 0x08, 0x8a, 0x41, 0x6c, 0xb7,
	0x12, 0x45, 0xca, 0x02, 0xbb, 0xfc, 0x09, 0xa5, 0xb1, 0xa9, 0x4c, 0xdb, 0xa4, 0x4c, 0x52, 0xd0,
	0x8a, 0x8b, 0x6a, 0x92, 0xcc, 0xa6, 0x56, 0x1d, 0x3b, 0xd8, 0xe3, 0x15, 0x41, 0xe2, 0x9a, 0x27,
	0xe1, 0x11, 0xe0, 0xad, 0x78, 0x01, 0xae, 0xd0, 0xcc, 0x38, 0xce, 0x38, 0x3f, 0xc0, 0x5d, 0xce,
	0xf9, 0xbe, 0x73, 0xce, 0xcc, 0xe7, 0x6f, 0x26, 0x03, 0x7b, 0x13, 0x12, 0x3e, 0x52, 0x36, 0xf5,
	0xc8, 0x90, 0x9e, 0x4f, 0xc3, 0x80, 0x05, 0xa8, 0x14, 0x05, 0xfe, 0xa4, 0xa1, 0x0d, 0xdc, 0x91,
	0x4c, 0x34, 0x6a, 0x03, 0x77, 0xec, 0xfa, 0x2c, 0x89, 0x76, 0x5d, 0x9f, 0x13, 0x7c, 0x97, 0xcc,
	0x13, 0xcc, 0x9d, 0xd0, 0x88, 0x91, 0xc9, 0x54, 0x26, 0xcc, 0x2b, 0xd0, 0x2f, 0x29, 0xeb, 0x86,
	0x23, 0x1a, 0x46, 0x98, 0xfe, 0x14, 0xd3, 0x88, 0xa1, 0x77, 0xa1, 0x1c, 0xf0, 0x84, 0x91, 0x3f,
	0xc9, 0x9f, 0x56, 0x9b, 0xd5, 0x73, 0xde, 0xe3, 0x5c, 0x70, 0xb0, 0x44, 0xd0, 0x01, 0x94, 0x87,
	0x41, 0xec, 0x33, 0xa3, 0x70, 0x92, 0x3f, 0x2d, 0x61, 0x19, 0x98, 0x9f, 0x40, 0x5d, 0x69, 0x36,
	0xf5, 0x66, 0xe8, 0x3d, 0xa8, 0x88, 0x82, 0xc8, 0xc8, 0x9f, 0x14, 0x97, 0x7b, 0x25, 0x90, 0xf9,
	0x47, 0x01, 0xd0, 0x25, 0x65, 0xb7, 0x61, 0x30, 0xa4, 0x51, 0xe4, 0xfa, 0x63, 0x59, 0xfb, 0x65,
	0x5a, 0x5b, 0x10, 0xb5, 0xef, 0xcb, 0xda, 0x55, 0xa6, 0x6c, 0x17, 0xd9, 0x3e, 0x0b, 0x67, 0xf3,
	0xa6, 0x8d, 0x5f, 0xa1, 0x9e, 0xd0, 0xe8, 0x48, 0xe0, 0xa8, 0x0e, 0x05, 0x77, 0x24, 0xf6, 0xa4,
	0xe1, 0x82, 0x3b, 0x42, 0x47, 0x50, 0x89, 0x18, 0x61, 0x71, 0x24, 0x36, 0xb1, 0x83, 0x93, 0x08,
	0x7d, 0x08, 0x5a, 0xaa, 0x92, 0x51, 0x14, 0x12, 0xec, 0xca, 0xd1, 0xfd, 0x79, 0x1a, 0x2f, 0x18,
	0x5c, 0x0a, 0xfa, 0x33, 0x0b, 0x89, 0x51, 0x12, 0x9d, 0x65, 0xd0, 0x18, 0x40, 0x55, 0x59, 0x15,
	0xd2, 0xa1, 0xf8, 0x48, 0x67, 0xc9, 0x70, 0xfe, 0x13, 0x7d, 0x05, 0xe5, 0x37, 0xc4, 0x8b, 0xa9,
	0x18, 0x5e, 0x6d, 0x3e, 0xdd, 0xb8, 0xb9, 0xec, 0x2e, 0xb0, 0xac, 0xfa, 0xbc, 0xf0, 0x32, 0x6f,
	0x7e, 0x00, 0xa8, 0x1f, 0xc4, 0xc3, 0x87, 0xec, 0xd7, 0xd3, 0xa1, 0xe8, 0x58, 0x52, 0x6f, 0x0d,
	0xf3, 0x9f, 0xe6, 0xef, 0x25, 0x80, 0x1b, 0x61, 0x1d, 0x8b, 0x12, 0x6f, 0x45, 0x87, 0xb7, 0x01,
	0x06, 0xd4, 0x1f, 0x3e, 0x70, 0x77, 0x49, 0xad, 0x4b, 0x58, 0xc9, 0x70, 0x3c, 0x8a, 0xa7, 0x53,
	0xcf, 0xa5, 0xa1, 0x63, 0x09, 0x41, 0x34, 0xac, 0x64, 0x38, 0x3e, 0x0c, 0xfc, 0x28, 0x9e, 0x08,
	0x5c, 0xaa, 0xa0, 0x64, 0x50, 0x03, 0xb6, 0x27, 0x24, 0x62, 0x02, 0x2d, 0x0b, 0x34, 0x8d, 0xb9,
	0x78, 0x24, 0x7a, 0x74, 0x2c, 0xa3, 0x22, 0xc5, 0x13, 0x01, 0xcf, 0x0e, 0xdc, 0x91, 0x63, 0x19,
	0x5b, 0x32, 0x2b, 0x02, 0xde, 0x67, 0x14, 0x87, 0x84, 0xb9, 0x81, 0x6f, 0x6c, 0x0b, 0xdb, 0xa5,
	0x31, 0x32, 0xa1, 0x3c, 0x0d, 0xdd, 0x21, 0x35, 0x34, 0xa1, 0x66, 0x4d, 0xaa, 0x79, 0xe1, 0x8e,
	0x1d, 0x9f, 0x61, 0x09, 0xf1, 0xef, 0x1a, 0x31, 0x12, 0x32, 0xfe, 0x15, 0x0d, 0xd8, 0xf0, 0x5d,
	0x53, 0x06, 0x7a, 0x06, 0x5b, 0xd4, 0x1f, 0x09, 0x72, 0x75, 0x3d, 0x79, 0x8e, 0xa3, 0xf3, 0xd4,
	0x49, 0xb5, 0x93, 0xfc, 0x69, 0xbd, 0x79, 0x24, 0x99, 0x0b, 0xcd, 0x7b, 0x02, 0x4d, 0x1d, 0xf6,
	0x31, 0xd4, 0x07, 0x5e, 0x30, 0x7c, 0xa4, 0xa3, 0x0b, 0xe2, 0x11, 0x7f, 0x48, 0x8d, 0x9d, 0x35,
	0xcb, 0x5e, 0xe2, 0xa0, 0x73, 0xa8, 0xb2, 0x80, 0x11, 0xef, 0x96, 0xcc, 0x82, 0x98, 0x19, 0xf5,
	0x35, 0x25, 0x2a, 0x01, 0x7d, 0x04, 0xe0, 0x91, 0x88, 0x5d, 0xb8, 0x9e, 0xd7, 0xef, 0x19, 0xbb,
	0xeb, 0xf7, 0xa0, 0x50, 0xcc, 0xbf, 0x8b, 0x50, 0x95, 0x6b, 0xde, 0x78, 0x60, 0x46, 0x94, 0x78,
	0x8e, 0x25, 0x3c, 0xab, 0xe1, 0x24, 0x42, 0xcf, 0x41, 0x13, 0x87, 0xae, 0x3f, 0x9b, 0x52, 0xe1,
	0x8f, 0x7a, 0xf3, 0x50, 0x55, 0xa0, 0x3b, 0x07, 0xf1, 0x82, 0x87, 0x3e, 0x83, 0xaa, 0x08, 0xa4,
	0x34, 0xc2, 0x36, 0xf5, 0xe6, 0x93, 0x95, 0xb2, 0x44, 0x39, 0x95, 0xcb, 0xd7, 0x41, 0x62, 0xf6,
	0x10, 0x84, 0x89, 0x9d, 0x92, 0x08, 0x99, 0x50, 0x13, 0xf7, 0x10, 0x0d, 0xa7, 0x24, 0x64, 0xb3,
	0xc4, 0x53, 0x99, 0xdc, 0xc2, 0x28, 0x5b, 0x9b, 0x8d, 0xf2, 0x6f, 0x46, 0x6b, 0xc0, 0xb6, 0x4f,
	0xd9, 0x6b, 0x8f, 0x8c, 0x23, 0x43, 0x3b, 0x29, 0x9e, 0x6e, 0xe3, 0x34, 0x46, 0x5f, 0xc3, 0x8e,
	0x3b, 0xa2, 0x3e, 0x73, 0xd9, 0xec, 0x9a, 0xbe, 0xa1, 0x9e, 0x30, 0x59, 0xbd, 0x79, 0xac, 0x6e,
	0xca, 0x51, 0x09, 0x38, 0xcb, 0x47, 0x6f, 0x81, 0x36, 0xf0, 0xc8, 0xf0, 0xd1, 0x73, 0x23, 0x26,
	0x4c, 0xa7, 0xe1, 0x45, 0x82, 0x1f, 0x6c, 0x46, 0xc6, 0xc2, 0x62, 0x35, 0xcc, 0x7f, 0x2e, 0x9d,
	0xdc, 0x9d, 0x95, 0x93, 0x7b, 0x06, 0xda, 0xeb, 0x30, 0xf8, 0x85, 0xfa, 0xbd, 0x78, 0xb2, 0xd6,
	0x2f, 0x0b, 0xd8, 0xfc, 0x2b, 0x0f, 0x7b, 0xdc, 0xaa, 0xed, 0x07, 0xe2, 0x8f, 0xe9, 0xfc, 0x32,
	0xf9, 0xbf, 0x16, 0x78, 0x01, 0xd5, 0x50, 0x96, 0xfc, 0xb7, 0x09, 0x54, 0x66, 0x46, 0xeb, 0xd2,
	0xa6, 0x43, 0x5d, 0xde, 0xfc, 0xad, 0x5e, 0xa4, 0x47, 0xaf, 0x22, 0x66, 0xbe, 0xa3, 0xce, 0xcc,
	0xec, 0x25, 0x7b, 0x06, 0xcf, 0x5a, 0xb0, 0xbb, 0xb4, 0x30, 0x54, 0x07, 0xb8, 0x69, 0xe1, 0x2b,
	0xbb, 0x7f, 0xdf, 0xea, 0xbc, 0xd2, 0x73, 0x4a, 0x7c, 0xe1, 0x58, 0x7a, 0x5e, 0xc5, 0x7b, 0x57,
	0x7a, 0xe1, 0xec, 0x12, 0xf6, 0x56, 0x9c, 0x8a, 0x8e, 0xe1, 0x30, 0x21, 0x75, 0xb1, 0x65, 0xe3,
	0x7b, 0xa7, 0xd3, 0x6a, 0xf7, 0x9d, 0xef, 0x6d, 0x3d, 0x87, 0x9e, 0xc0, 0x7e, 0x06, 0x4a, 0x80,
	0xfc, 0xd9, 0x8f, 0xb0, 0xbf, 0xc6, 0x1d, 0xe8, 0x00, 0xf4, 0x74, 0x3d, 0xdd, 0x8e, 0x73, 0xd3,
	0xbd, 0xeb, 0x65, 0xba, 0xdc, 0xf6, 0xec, 0x3b, 0xab, 0xdb, 0x79, 0x25, 0x80, 0x3c, 0x3a, 0x84,
	0xbd, 0x04, 0x70, 0x2c, 0xbb, 0xd3, 0x77, 0xbe, 0x71, 0x6c, 0x4b, 0x2f, 0x9c, 0x0d, 0x41, 0x5f,
	0xbe, 0x88, 0x94, 0x45, 0xf6, 0xfa, 0xad, 0xfe, 0x5d, 0xef, 0xfe, 0xae, 0x73, 0xd5, 0xe9, 0xfe,
	0xd0, 0xd1, 0x73, 0xa8, 0x01, 0x47, 0x59, 0xa8, 0xd5, 0x6e, 0xdb, 0xb7, 0x7d, 0x9b, 0x0b, 0x60,
	0xc0, 0x41, 0x16, 0x6b, 0x5f, 0x77, 0x7b, 0x62, 0xc8, 0x6f, 0x79, 0x38, 0xde, 0xa8, 0x39, 0xda,
	0x87, 0x5d, 0x6c, 0x7f, 0x77, 0x67, 0xf7, 0xfa, 0xca, 0x20, 0x25, 0xd9, 0xc6, 0x76, 0x4b, 0x4e,
	0x38, 0x00, 0x3d, 0x4d, 0xb6, 0x3a, 0x6d, 0xfb, 0x9a, 0x77, 0x57, 0xb3, 0xd8, 0xfe, 0xd6, 0x6e,
	0x73, 0x6e, 0x51, 0xcd, 0xa6, 0x6b, 0x2c, 0x35, 0xff, 0x2c, 0x40, 0x45, 0xae, 0x04, 0x7d, 0x01,
	0x5a, 0xfa, 0x1c, 0x41, 0x47, 0xe9, 0x1f, 0x6c, 0xe6, 0xef, 0xb2, 0x71, 0xb0, 0x92, 0x9f, 0x7a,
	0x33, 0x33, 0x87, 0x9e, 0x41, 0xb5, 0x1d, 0x52, 0xc2, 0xa8, 0xbc, 0x0b, 0xd5, 0x87, 0x4b, 0x43,
	0x0d, 0xcc, 0x1c, 0x7a, 0x0a, 0xb5, 0x79, 0xf9, 0xc5, 0xcc, 0xb1, 0xd0, 0xb6, 0x84, 0x1d, 0x6b,
	0x99, 0xc8, 0x7b, 0xf2, 0xab, 0xdc, 0xdb, 0xdc, 0xd3, 0x9e, 0x4c, 0x19, 0x1f, 0xff, 0x12, 0x76,
	0x32, 0x6f, 0x01, 0xa4, 0xe2, 0x0d, 0x63, 0xd3, 0x6b, 0xc1, 0xcc, 0xa1, 0x4f, 0xa1, 0xaa, 0xbc,
	0x0a, 0x50, 0x42, 0x5d, 0x7d, 0x28, 0x2c, 0x4d, 0x1c, 0x54, 0xc4, 0x83, 0xf0, 0xf9, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x40, 0xbe, 0x4c, 0x17, 0x66, 0x0a, 0x00, 0x00,
}
